### ISSUE TITLE
error admin or none

### ISSUE THREAD

**Issue by Martycat111** [TheFreeWeb/FreeSearcher#9]
admin make cant find "cmd1.bat" 
lots of "perms denied messages with the search bats when not admin

**Comment by Martycat111** [comment]
![Screenshot 2024-09-20 091704](https://github.com/user-attachments/assets/c37bc699-ae87-40d6-a88d-b4481b3baa92)
![Screenshot 2024-09-20 092041](https://github.com/user-attachments/assets/535ee3f5-c58b-45c3-9ed1-8f84e3999cd4)
eEe

**Comment by WooRepo** [comment]
Can you send a video replicating?

**Comment by WooRepo** [comment]
Ohhh... you cannot run start.bat to execute the program.

**Comment by Martycat111** [comment]
I wasnt

**Comment by Martycat111** [comment]
but video it is

**Comment by WooRepo** [comment]
Hmmmm.... lemme try replicate!

**Comment by WooRepo** [comment]
Oh, and I made the python thing work :)

**Comment by WooRepo** [comment]
What did you run to start the program?

**Comment by WooRepo** [comment]
ARENT YOU AT BLOODY SCHOOL.

**Comment by Martycat111** [comment]
what python thing work?

**Comment by Martycat111** [comment]
btw can I have op on the linkdeer one to add stuf

**Comment by Martycat111** [comment]
geez there are a lot of errors for the "new python version"
also add list PLSLLS

**Comment by Martycat111** [comment]
i ran the start.bat

**Comment by Martycat111** [comment]
:P

**Comment by WooRepo** [comment]
you can get it working...

**Comment by Martycat111** [comment]
How?

**Comment by Martycat111** [comment]
What do you mean?

**Comment by Martycat111** [comment]
I’m gonna add a funny windows xp error sound for errors >:)

**Comment by Martycat111** [comment]
Then I’ll add the stupid new functionality
(On a dum iPad)

**Comment by WooRepo** [comment]
Why are you so pissed?

**Comment by Martycat111** [comment]
Because of the new version which i dont understand and its lack of commands and the fact that i can’t copy the windows version if it doesn’t work

**Comment by Martycat111** [comment]
Plus the python version is quite rough and buggy 🛺🦠🕷️

**Comment by WooRepo** [comment]
Ya, but we can improve and add commands, its just a base

**Comment by WooRepo** [comment]
Alf?

**Comment by Martycat111** [comment]
R u there

**Comment by WooRepo** [comment]
ye

**Comment by WooRepo** [comment]
wanna chat?

**Comment by Martycat111** [comment]
Oh cool i added a form for submitting media

**Comment by WooRepo** [comment]
Ik, i memed. EHEHEHHEHEH

**Comment by Martycat111** [comment]
What do you mean

**Comment by WooRepo** [comment]
I submitted a joke response

**Comment by Martycat111** [comment]
Oh ok

**Comment by Martycat111** [comment]
I can only have one tab open at a time cos I’m on an ipad

**Comment by WooRepo** [comment]
Also, sorry about the new python version... but can you work with it... I mean, its a good base

**Comment by Martycat111** [comment]
Yeah! It’s fine ill help

**Comment by WooRepo** [comment]
Okk

**Comment by WooRepo** [comment]
wanna g meet?

**Comment by Martycat111** [comment]
Mabey

**Comment by Martycat111** [comment]
Ok i geus

**Comment by WooRepo** [comment]
lemme check with MOMMY

**Comment by Martycat111** [comment]
Gmail walfie308@gmail.com the link

**Comment by Martycat111** [comment]
Ill be on after lunch, which is rn

**Comment by WooRepo** [comment]
okk

**Comment by WooRepo** [comment]
Error log for playsound:

C:\Users\Woo\Downloads\epic-full\FreeSearcher-main (27)\FreeSearcher-main\python>pip install -r requirements.txt
Requirement already satisfied: requests in c:\users\woo\appdata\local\programs\python\python313\lib\site-packages (from -r requirements.txt (line 1)) (2.32.3)
Requirement already satisfied: tqdm in c:\users\woo\appdata\local\programs\python\python313\lib\site-packages (from -r requirements.txt (line 2)) (4.66.5)
Collecting playsound (from -r requirements.txt (line 3))
  Using cached playsound-1.3.0.tar.gz (7.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Woo\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\Woo\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Woo\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Woo\AppData\Local\Temp\pip-build-env-foq4rgjp\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Woo\AppData\Local\Temp\pip-build-env-foq4rgjp\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\Woo\AppData\Local\Temp\pip-build-env-foq4rgjp\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Woo\AppData\Local\Temp\pip-build-env-foq4rgjp\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 6, in <module>
        File "C:\Users\Woo\AppData\Local\Programs\Python\Python313\Lib\inspect.py", line 1254, in getsource
          lines, lnum = getsourcelines(object)
                        ~~~~~~~~~~~~~~^^^^^^^^
        File "C:\Users\Woo\AppData\Local\Programs\Python\Python313\Lib\inspect.py", line 1236, in getsourcelines
          lines, lnum = findsource(object)
                        ~~~~~~~~~~^^^^^^^^
        File "C:\Users\Woo\AppData\Local\Programs\Python\Python313\Lib\inspect.py", line 1078, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Martycat111** [comment]
you have error with downlaoding playsound

**Comment by Martycat111** [comment]
can you send gmeat link

**Comment by WooRepo** [comment]
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQudKd-nbZFq3dUHmZjnSzDGY65r_GJ11fMrQ&s

**Comment by Martycat111** [comment]
it works best in winyos

**Comment by Martycat111** [comment]
and google meet

**Comment by WooRepo** [comment]
sent

**Comment by Martycat111** [comment]
school?
or not

**Comment by WooRepo** [comment]
walfie

**Comment by Martycat111** [comment]
308?

**Comment by WooRepo** [comment]
yeh

**Comment by Martycat111** [comment]
oh got it
